on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.14]
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Enable corepack
        run: corepack enable
      - name: Node.js ${{ matrix.node-version }} (yarn)
        uses: actions/setup-node@v4
        id: yarn-cache
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install packages
        run: yarn install --immutable
      - name: Run tests
        run: yarn run test
